version: "3.9"
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: streamlit run main.py --server.port=8501 --server.address=0.0.0.0
